#!/usr/bin/env node

// eslint-disable-next-line @typescript-eslint/no-var-requires
const https = require('https');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require('fs');

const url =
  'https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json';

https
  .get(url, (res) => {
    let body = '';

    res.on('data', (chunk) => {
      body += chunk;
    });

    res.on('end', () => {
      try {
        const json = JSON.parse(body);
        const emojiArray = json.gitmojis.map((e) => e.emoji);
        fs.writeFileSync('gitmojis.json', JSON.stringify(emojiArray));
      } catch (error) {
        // eslint-disable-next-line no-console
        console.error(error.message);
      }
    });
  })
  .on('error', (error) => {
    // eslint-disable-next-line no-console
    console.error(error.message);
  });
