name: Notifier

on:
  issues:
    types: [opened]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Salve devs, nova Issue!
          [${{ github.repository }}#${{ github.event.issue.number}}](https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number}})